[project]
name = "hgx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastjsonschema>=2.21.1",
    "hypernetx>=2.4.0",
    "ipykernel>=6.29.5",
    "matchms>=0.28.2",
    "numpy==2.0.0",
]
